### ISSUE TITLE
openssl upgrade error

### ISSUE THREAD

**Issue by dunn** [Linuxbrew/linuxbrew#737] opened 2016-01-23 02:29 UTC
_From @vol7ron on January 23, 2016 0:43_

openssl seems to be a dependency for many scripts (ruby, curl, etc).  I have no `brew doctor` issues and `brew update` shows everything up to date.

    $HOME/.linuxbrew/opt/curl/bin/curl: symbol lookup error: \
       $HOME/.linuxbrew/lib/libcurl.so.4: undefined symbol: SSL_CTX_set_alpn_protos

I have download issues for that and 2 of the mirrors.  

_Copied from original issue: Homebrew/homebrew#48383_

**Comment by vol7ron** [comment] 2016-01-24 23:34
I also posted this issue in the Curl forum, soliciting help with tackling this:  https://github.com/bagder/curl/issues/362

**Comment by vol7ron** [comment] 2016-01-24 23:43
Just an FYI, I'm not posting this for me, but for other users that may encounter this issue.  My error, which had been resolved.  That was accomplished by simply removing curl and re-installing it:

    brew remove curl
    brew install curl

This re-downloads the _openssl_ dependency (in this case v1.0.2e) and then reinstalls _curl_.  What I'd like this issue thread to turn into is a discovery/debuggery of why there was an error in the first place and how it could be resolved in the future (for anyone else that may encounter a similar scenario).

I'm not sure if there was an issue with the original curl download (corruption, bad installation, etc) and it has since been fixed; or if this is a result of something I did after _curl_ was installed, which I may have forgotten.  It's possible that I may have created a CA on this VM when I was trying to patch OpenVPN on another box.

Regardless, I'd like to determine if this is something that needs to be investigated before it is closed and dismissed.

**Comment by sjackman** [comment] 2016-01-25 07:03
Hi. Without a recipe to reproduce the error I can only guess as to what happened. It looks as though curl was compiled against one version of `openssl` that included `SSL_CTX_set_alpn_protos` and was then later run using a different version of `openssl` that does not include that symbol. I can't say why that happened. The workaround as you discovered is `brew reinstall curl`

**Closed by sjackman** 2016-01-25 07:03 UTC
