### ISSUE TITLE
Python segfaults on import numpy if LD_LIBRARY_PATH points to missing directory

### ISSUE THREAD

**Issue by erigler-usgs** [Linuxbrew/linuxbrew#841] opened 2016-02-24 23:25 UTC
I know the title doesn't sound like a Linuxbrew issue, but please bear with me. On attempting to install matplotlib-basemap, I got a failed installation with no explanation. It turns out there was no explanation because the failure was due to a segmentation fault that arose when the setup.py script for matplotlib-basemap attempted to import numpy.

Now, as you probably know, Linuxbrew defines LD_LIBRARY_PATH as `$(brew --prefix pkg)/lib` when pkg is installed. This folder does not, in general, exist when a package is first installed. I discovered this while attempting to install matplotlib-basemap interactively with Linuxbrew. I also discovered that if I unset LD_LIBRARY_PATH, or simply set it equal to an existing folder, there were no segmentation faults when attempting to import numpy.

In an effort to distill this issue down to something very simple to facilitate reproduction, I did the following:

> brew install --interactive hello
> python -c 'import numpy'

...and got a segmentation fault. Then I did the following:

> brew install --interactive hello
> unset LD_LIBRARY_PATH
> python -c 'import numpy'

and got NO segmentation fault.

One final note, I tried the above with the -v option for Python, and it seems that the segmentation fault always happens when Python calls dlopen.

FWIW, mine is a Redhat Enterprise 6 system, with Linuxbrew standalone set up as per the instructions written up here (GitHub).

**Comment by sjackman** [comment] 2016-02-24 23:53
I'm not able to reproduce this bug myself, so it'll be difficult for me to troubleshoot.

```sh
$ LD_LIBRARY_PATH=/foo python -c 'import numpy'
$ echo $?
0
$ brew install -i hello
$ echo $?
0
```

Does the following patch help?
```diff
diff --git a/Library/Homebrew/extend/ENV/std.rb b/Library/Homebrew/extend/ENV/std.rb
index ea1b4d8..42b2ec7 100644
--- a/Library/Homebrew/extend/ENV/std.rb
+++ b/Library/Homebrew/extend/ENV/std.rb
@@ -58,6 +58,7 @@ module Stdenv
 
     if OS.linux? && !["glibc", "glibc25"].include?(formula && formula.name)
       # Add this formula's library directory to the shared library search path.
+      lib.mkdir_p if formula
       prepend "LD_LIBRARY_PATH", formula.lib, File::PATH_SEPARATOR if formula
 
       # Set the dynamic linker and library search path.
```

I probably won't commit it as is, but it could help for troubleshooting.

**Comment by eiennohito** [comment] 2016-02-25 08:03
Got the same bug when installing mongodb on CentOS 6.7 with brewed python.

Patch do not work for me:

```
/mnt/orange/brew/data/Library/brew.rb (Formulary::AliasLoader): loading /mnt/orange/brew/data/Library/Formula/mongodb.rb
/mnt/orange/brew/data/Library/brew.rb (Formulary::FormulaLoader): loading /mnt/orange/brew/data/Library/Formula/go.rb
/mnt/orange/brew/data/Library/brew.rb (Formulary::FormulaLoader): loading /mnt/orange/brew/data/Library/Formula/scons.rb
/mnt/orange/brew/data/Library/Homebrew/build.rb (Formulary::FromPathLoader): loading /mnt/orange/brew/data/Library/Formula/mongodb.rb
/mnt/orange/brew/data/Library/Homebrew/build.rb (Formulary::FormulaLoader): loading /mnt/orange/brew/data/Library/Formula/go.rb
/mnt/orange/brew/data/Library/Homebrew/build.rb (Formulary::FormulaLoader): loading /mnt/orange/brew/data/Library/Formula/scons.rb
/mnt/orange/brew/data/Library/Homebrew/build.rb (Formulary::FormulaLoader): loading /mnt/orange/brew/data/Library/Formula/git.rb
Error: undefined local variable or method `lib' for #<Object:0x00000001c99158>
Please report this bug:
    https://github.com/Linuxbrew/linuxbrew/blob/master/share/doc/homebrew/Troubleshooting.md#troubleshooting
/mnt/orange/brew/data/Library/Homebrew/extend/ENV/std.rb:61:in `setup_build_environment'
/mnt/orange/brew/data/Library/Homebrew/build.rb:91:in `install'
/mnt/orange/brew/data/Library/Homebrew/build.rb:177:in `<main>'
```

**Comment by erigler-usgs** [comment] 2016-02-25 16:07
The patch works for me with a minor tweak:

```diff
diff --git a/Library/Homebrew/extend/ENV/std.rb b/Library/Homebrew/extend/ENV/std.rb
index ea1b4d8..42b2ec7 100644
--- a/Library/Homebrew/extend/ENV/std.rb
+++ b/Library/Homebrew/extend/ENV/std.rb
@@ -58,6 +58,7 @@ module Stdenv

     if OS.linux? && !["glibc", "glibc25"].include?(formula && formula.name)
       # Add this formula's library directory to the shared library search path.
+      FileUtils.mkdir_p formula.lib if formula
       prepend "LD_LIBRARY_PATH", formula.lib, File::PATH_SEPARATOR if formula

       # Set the dynamic linker and library search path.
```
I know this is probably a fairly obscure issue that doesn't even manifest in more up-to-date Linux systems, but it never cropped up until the relatively recent changes to make most/all Linuxbrew packages dependent on a Linuxbrew's glibc, binutils, etc. I hope you will find some way to include this "fix", however inelegant you think it might be, to help those of us forced to work on older systems.

**Comment by sjackman** [comment] 2016-02-25 17:10
I have a thought. Was your `python` installed before `glibc` was installed? I bet your `python` is using your system's `ld.so`, but Homebrew's `libc`, which can cause grief. https://gist.github.com/anonymous/7e1f2d793dd43cc22e31#file-00-config-out-L12
Please report `readelf -l `which python` |grep interpreter`
After that, please try `brew patchelf python`. Any chance it starts to work without this patch after that?

**Comment by erigler-usgs** [comment] 2016-02-25 17:39
No, python was installed after glibc, since after several recent failed upgrades, I chose to wipe my Linuxbrew and start over from scratch, following the standalone instructions this time.

...but here's the requested information anyway:

```
1011 <~> readelf -l `which python` | grep interpreter
      [Requesting program interpreter: /home/erigler/local/opt/glibc/lib/ld-linux-x86-64.so.2]
```

And  `patchelf python` didn't change anything.

**Comment by sjackman** [comment] 2016-02-25 17:56
Okay. Thanks for trying. 

This appears to be a known bug in glibc 2.19! I really don't know why it affects you but doesn't affect me. I'm also using glibc 2.19 built from Linuxbrew. I'd be curious to know why if you're able to figure it out.

Adding a second path to `LD_LIBRARY_PATH` that definitely exists (but is harmless) might also work around this issue. Can you try that?

This bug is fixed in glibc 2.20, but I haven't figured out yet how to upgrade `glibc` without breaking everything. I'll have to work on that.

Here's the bug report:
https://bugzilla.redhat.com/show_bug.cgi?id=1184234
https://bodhi.fedoraproject.org/updates/glibc-2.20-8.fc21
And here's a patch!
https://sourceware.org/ml/libc-alpha/2014-10/msg00328.html

**Comment by erigler-usgs** [comment] 2016-02-25 18:19
Thanks for the info...you are clearly more practiced than I at tracking down bugs like this.

And prepending a path to an existing, but empty, folder does seem to fix the problem too (in my case, I added a path to an unused /usr/local/lib folder).

But, I'm not sure how to guarantee an empty-but-existing folder, except to create it yourself, in which case we're back to the original solution.

**Comment by sjackman** [comment] 2016-02-25 18:47
Perhaps this patch is okay as is then.

Any chance your `curl` fails to download `git` in `brew install git` but works with `brew fetch git` as in #797?

**Comment by sjackman** [comment] 2016-02-25 18:48
Is `FileUtils.` necessary? Does `mkdir_p formula.lib if formula` work? If not, which `ruby --version` are you using?

**Comment by erigler-usgs** [comment] 2016-02-25 19:04
The empty lib directory is removed after installation, and also if installation is cleanly aborted.

I installed git with `brew install git`, with no issues like #797.

Finally, I get a ``undefined method `mkdir_p' `` error if I don't use FileUtils.

**Comment by sjackman** [comment] 2016-02-25 19:13
> I installed git with brew install git, with no issues like #797.

Were you able to instal `git` without this patch?
```sh
rm -f `brew --cache`/git-*
brew install git
```

**Comment by erigler-usgs** [comment] 2016-02-25 19:19
Yes. When I return std.rb to its pristine state, then uninstall git and remove its cached files, I am able to install git with a simple `brew install git`. It freshly downloads git, git-manpages, and git-htmldocs with no problems, then installs them successfully.

**Comment by sjackman** [comment] 2016-02-25 19:23
Thanks for clarifying. I was hoping that these were the same bugs. Oh well.

**Comment by sjackman** [comment] 2016-02-25 19:27
I'm able to reproduce this bug! `brew install mongodb` fails for me.
```
BuildError: Failed executing: /gsc/btl/linuxbrew/opt/scons/bin/scons install --prefix=/gsc/btl/linuxbrew/Cellar/mongodb/3.2.3 -j24 CC=/gsc/btl/linuxbrew/bin/gcc-5 CXX=/gsc/btl/linuxbrew/bin/g++-5\ -std=c++11 --use-new-tools
bash-3.2$ /gsc/btl/linuxbrew/opt/scons/bin/scons install --prefix=/gsc/btl/linuxbrew/Cellar/mongodb/3.2.3 -j24 CC=/gsc/btl/linuxbrew/bin/gcc-5 CXX=/gsc/btl/linuxbrew/bin/g++-5 -std=c++11 --use-new-tools
Segmentation fault
```
With this patch, it gets further than this! (but still fails later, see #845).
I'm applying your patch. Thanks for troubleshooting a very difficult issue. I'm not sure how long it would have taken me to figure this out without your help.

Would you like to submit a pull request for this fix? You've certainly earned it.

**Comment by erigler-usgs** [comment] 2016-02-25 19:30
Thanks, but I think I'll leave this to you. I am quite a novice at Github, and I might totally flub the pull request.

**Comment by sjackman** [comment] 2016-02-25 19:48
Fixed! Thanks for your help @erigler-usgs

**Closed** 2016-02-25 19:48 UTC
Labels: bug

**Comment by sjackman** [comment] 2016-02-29 20:56
Our fix unfortunately breaks unpacking any source archive that includes a directory named `lib`, such as `gcc`. :cry:
See https://github.com/Linuxbrew/linuxbrew/pull/869#issuecomment-190360110
