### ISSUE TITLE
texlive.rb

### ISSUE THREAD

**Issue by jwhite007** [Linuxbrew/linuxbrew#893] opened 2016-03-06 15:20 UTC
Wrong sha256 hash. It should be "f4ad5f49c01173de651b3aa4c0a74eac0166e2f3d341de4f8775d31fe2c136bb"

**Comment by sjackman** [comment] 2016-03-07 05:28
Thanks for the bug report, James. It's fixed now.

**Closed** 2016-03-07 05:28 UTC

**Comment by jwhite007** [comment] 2016-03-11 17:06
The developers seem to be changing this file quite a bit. The new sha256 hash is now being reported as "426ded64b355df4a69d3fa6939b15c34ea20000c4788643193b3d272cac9bf5c"

**Comment by sjackman** [comment] 2016-03-11 17:18
Can you please submit a pull request to update the version and sha256?

Perhaps I'll bottle the installer, and move the network installation to `postinstall`.

**Comment by jwhite007** [comment] 2016-03-11 18:41
I'll submit a pull request... reading the tutorial now. A bottle would be great as the build takes forever.

**Comment by jwhite007** [comment] 2016-03-15 00:13
I haven't quite gotten to finishing this off. I've been suffering from the flu. I'm going to go home and rest now, but upon...
```
brew tests
```
i got...
```
Tasks: TOP => test
(See full trace by running task with --trace)
Warning: File leak is detected
FormulaLockTests#test_locking_file_with_existing_lock_raises_error
--- expected
+++ actual
@@ -2,6 +2,7 @@
  "/cache",
  "/cellar",
  "/formula_cache",
+ "/formula_cache/.nfs0000000000afc86b00000243",
  "/logs",
  "/prefix",
  "/prefix/Library",
DependencyExpansionTests#test_expand_keeps_recommendeds_by_default
--- expected
+++ actual
@@ -2,7 +2,6 @@
  "/cache",
  "/cellar",
  "/formula_cache",
- "/formula_cache/.nfs0000000000afc86b00000243",
  "/logs",
  "/prefix",
  "/prefix/Library",
```
I'll try to troubleshoot tomorrow.

**Comment by sjackman** [comment] 2016-03-15 04:38
Those `.nfs*` files should be ignored by the `File leak` test.

**Comment by jwhite007** [comment] 2016-03-21 03:32
I apologize for the delay on this. I recovered from the flu and then had to play catch-up at work. I'm running into some oddities. I've created a branch to make my changes to texlive. I've named it "texlive." After...
```
git checkout texlive
brew edit texlive
git checkout master
brew cat texlive
```
...I've noticed that my changes are on master. According to my knowledge of git, this shouldn't be the case... correct?

**Comment by rwhogg** [comment] 2016-03-21 03:40
> ...I've noticed that my changes are on master. According to my knowledge of git, this shouldn't be the case... correct?

Depends, IIRC:

1. If there are conflicts between your edits to `texlive` and the version on master, then it should outright block the branch switch.
2. If there are no conflicts, then your changes are automatically applied to master. (I don't think that's how git actually does it, but that's the net effect).

**Comment by sjackman** [comment] 2016-03-21 05:07
@jwhite007 You only missed one step, the `git commit`.

```
brew update
cd $(brew --prefix)
git checkout -b texlive origin/master
brew edit texlive
git commit -m 'texlive 20160305' Library/Formula/texlive.rb
git push jwhite007 texlive
# open a pull request
git checkout master
brew cat texlive
```

**Comment by jwhite007** [comment] 2016-03-21 13:14
Hmmm. Interesting. I thought the branches would be seen by git as different before the commit.

**Comment by jwhite007** [comment] 2016-03-21 15:20
I'm a little disturbed as to the activity on this file...

>http://ctan.mirrors.hoobly.com/systems/texlive/tlnet/
>19-Mar-2016 19:19
>3ca8979e5996397845ec0597c33a9bc8b4c1713aed74e97d62b96024a4aaadfd
>
>http://mirrors.acm.jhu.edu/ctan/systems/texlive/tlnet/
>19-Mar-2016 02:19
>eb6b6bb8a885c5b9dfbed30c17ede1c24a74f08facef510231e733be238e84df
>
>http://mirrors.concertpass.com/tex-archive/systems/texlive/tlnet/
>undated
>3ca8979e5996397845ec0597c33a9bc8b4c1713aed74e97d62b96024a4aaadfd
>
>http://ctan.mackichan.com/systems/texlive/tlnet/
>20-Mar-2016 02:19
>ad8e5ace82989eb3991f407f549e251c684e73bc656bbeb2f29d1c72557505b8
>
>http://mirrors.ibiblio.org/CTAN/systems/texlive/tlnet/
>2016-Mar-19 22:19:00
>3ca8979e5996397845ec0597c33a9bc8b4c1713aed74e97d62b96024a4aaadfd

I viewed all of these pages within 5 minutes.

**Comment by sjackman** [comment] 2016-03-21 19:05
We need to find a stable mirror for this file with a versioned file name. We could archive it ourself on BinTray.

**Comment by jwhite007** [comment] 2016-03-23 14:37
I'm working on finding a stable mirror which reports an sha256.

**Comment by jwhite007** [comment] 2016-03-24 14:21
I really think something odd is happening with those redirect mirror tar.gzs. I've found several sites, such as http://ctan.math.washington.edu/tex-archive/systems/texlive/Source/, that show stable tar.gzs for texlive. Is it possible to list several download sites in the rb. I see that the rb for R has the following...
>url "http://cran.rstudio.com/src/base/R-3/R-3.2.4-revised.tar.gz"
mirror "http://cran.r-project.org/src/base/R-3/R-3.2.4-revised.tar.gz"

Ostensibly if the download from "url" fails then a download from "mirror" is attempted... correct?
There are several sites, such as the UW site above, with stable texlive tar.gzs.

Also... When a site offers the tar.gz, but no sha256, how are the rb writers dealing with this? Do they download and hash several times and then publish the sha256 in the rb once they're sure their download is not corrupted? The two sites above for R, for instance, don't offer the hashes.

**Comment by sjackman** [comment] 2016-03-24 18:42
> Ostensibly if the download from "url" fails then a download from "mirror" is attempted... correct?

Correct.

> When a site offers the tar.gz, but no sha256, how are the rb writers dealing with this?

The contributor of the formula downloads the file and calculates the sha256.

The issue is that the file name is not versioned, and the developers update that file regularly.
We need to either cache the copy that we've downloaded on Bintray, or find a stable, versioned mirror.
