### ISSUE TITLE
Core/Formula separation 

### ISSUE THREAD

**Issue by xu-cheng** [Linuxbrew/linuxbrew#1033] opened 2016-04-02 14:15 UTC
@sjackman 

Just remind that we have shipped core/formula separation on Homebrew. 
Here is a TODO list for you to perform core/formula separation. **NOTE: THE ORDER MATTERS**

* Create a new `Linuxbrew/brew` repo. You could either fork `Homebrew/brew` then apply the diff between `Homebrew/brew` and `Linuxbrew/linuxbrew`. OR you could use following script then apply the missing change.
```bash
git filter-branch -f --prune-empty \
  --index-filter \
  'git rm --cached --ignore-unmatch -r -q -- Library/Formula Library/Aliases ;' \
  -- --all
```

+ Update `Linuxbrew/homebrew-core` repo to sync with `Linuxbrew/linuxbrew` and `Homebrew/homebrew-core`.
+ Update https://github.com/Homebrew/brew/blob/master/Library/Homebrew/tap.rb#L450-L454 to point to new `Linuxbrew/homebrew-core` repo.
+ Update https://github.com/Homebrew/brew/blob/master/Library/Homebrew/cmd/update.sh#L9-L15 to point to new `Linuxbrew/brew` repo.
+ Update Linuxbrew to the sync with `Homebrew/homebrew` with https://github.com/Homebrew/legacy-homebrew/blob/master/Library/Homebrew/cmd/update.sh#L9-L15 point to proper url. **This need to be done in the last step**.
+ Maybe some document cleanup?

**Comment by sjackman** [comment] 2016-04-03 19:21
Thanks for the heads up and instructions, Xu.

**Comment by sjackman** [comment] 2016-04-03 20:35
@Linuxbrew/core The upstream Homebrew repository has been split into `brew`, the package manager, and `Homebrew-core`, the formula. Linuxbrew will adopt this split as well some time next week. If you have any open pull requests that you'd like to commit before the split, now's the time to do it. =)

**Comment by sjackman** [comment] 2016-04-12 06:30
See Homebrew/legacy-homebrew#49752
and Homebrew/brew#1

**Comment by xu-cheng** [comment] 2016-04-12 06:32
The two issues in your last comment are outdated. I suggest you reference to https://github.com/Homebrew/legacy-homebrew/issues/50650 for comprehensive list.

**Comment by sjackman** [comment] 2016-04-12 06:41
> Create a new Linuxbrew/brew repo. You could either fork Homebrew/brew then apply the diff between Homebrew/brew and Linuxbrew/linuxbrew. OR you could use following script then apply the missing change.

I'd rather not lose the history, so that `git blame` is still useful, so I'll use your script.

**Comment by sjackman** [comment] 2016-04-12 06:42
> Update Linuxbrew/homebrew-core repo to sync with Linuxbrew/linuxbrew and Homebrew/homebrew-core.

By this you mean bring `Linuxbrew/homebrew-core` up to date by merging the changes from `Linuxbrew/linuxbrew` and `Homebrew/homebrew-core` into `Linuxbrew/homebrew-core`?

**Comment by xu-cheng** [comment] 2016-04-12 06:43
> By this you mean bring Linuxbrew/homebrew-core up to date by merging the changes from Linuxbrew/linuxbrew and Homebrew/homebrew-core into Linuxbrew/homebrew-core?

Yes, you should make `Linuxbrew/homebrew-core` sync with `Linuxbrew/linuxbrew` then with `Homebrew/homebrew-core`.

**Comment by sjackman** [comment] 2016-04-12 06:44
> Update Linuxbrew to the sync with Homebrew/homebrew with https://github.com/Homebrew/legacy-homebrew/blob/master/Library/Homebrew/cmd/update.sh#L9-L15 point to proper url. This need to be done in the last step.

And by this you mean merge `Homebrew/legacy-homebrew` into `Linuxbrew/linuxbrew`.

Last step is to rename `Linuxbrew/linuxbrew` to `Linuxbrew/legacy-linuxbrew`.

**Comment by xu-cheng** [comment] 2016-04-12 06:46
> And by this you mean merge Homebrew/legacy-homebrew into Linuxbrew/linuxbrew.

Yeap. 

> Last step is to rename Linuxbrew/linuxbrew to Linuxbrew/legacy-linuxbrew.

This is optional step.

Also, you can reach me on Slack for more special questions.

**Comment by sjackman** [comment] 2016-04-12 06:51
Thanks, Xu. I appreciate your help!

**Comment by sjackman** [comment] 2016-04-12 06:51
`Linuxbrew/linuxbrew:master` is currently behind `Homebrew/legacy-homebrew:master` by 32 commits:
```
a7058e0 readme: clarify what's not in homebrew/brew [Alex Dunn]
7d148dc update: use --replace-all to set remote.origin.fetch [Xu Cheng]
6146a1c README: note migrations. [Mike McQuaid]
130bc02 Update/split documentation. [Mike McQuaid]
d32d78d various: add remote migration hack [Xu Cheng]
5f53fc3 update: migrate to new remote [Xu Cheng]
235d819 test-bot: exclude Taps dir from root cleanup [Andrew Janke]
1e92c7f test-bot: have --cleanup clean core repo as well as tested tap [Andrew J
48e5079 test-bot: fix path in cleanup_before [Xu Cheng]
ef6cbe9 pull: fix --legacy when pulling bottle from new repo [Xu Cheng]
e13ff62 Revert "test-bot: clean up on Jenkins before building PR" [Martin Afanas
51e4e64 test-bot: clean up on Jenkins before building PR [Martin Afanasjew]
ef70efa diagnostic: improve check for 'install_name_tool' [Mike McQuaid]
60f8861 test-bot: ensure tap is full clone [Xu Cheng]
73bece8 test-bot: fix CI upload for core tap [Xu Cheng]
fc80d72 pull: auto fix legacy closes message [Xu Cheng]
c38cbf5 pull: fallback to old BrewTestBot git repo when necessary [Xu Cheng]
6ed1425 test-bot: handle legacy formulae PR from Homebrew/homebrew [Xu Cheng]
71cba60 doc: update for core/formula separation [Xu Cheng]
dc94fbc tap-(un)pin/untap: better error message [Xu Cheng]
68d6718 update-test: fix git fork bomb [Xu Cheng]
b3aadea pull: add --legacy flag [Xu Cheng]
edb7e9f bump Homebrew version to 0.9.8 [Xu Cheng]
1e33dcb git: check homebrew/core existence before installing brewed git [Xu Chen
33404b3 fix brew tests [Xu Cheng]
af81f99 --version/config: show core tap information [Xu Cheng]
7417397 audit/test-bot/pull: fix for core/formula separation [Xu Cheng]
1d13a03 descriptions: update for core/formula separation [Xu Cheng]
deac0d8 update-report: update for core/formula separation [Xu Cheng]
bf41e3c remove migrate_taps [Xu Cheng]
c831b1e various: Homebrew/core is the core tap [Xu Cheng]
f4a303a introduce `Homebrew/core` tap as new default core tap. [Xu Cheng]
```

**Comment by sjackman** [comment] 2016-04-12 06:52
@xu-cheng Can all 32 commits be merged into `Linuxbrew/linuxbrew` at once (as the last step)?

**Comment by sjackman** [comment] 2016-04-12 06:52
There's a bunch of conflicts to resolve, but I'll deal with that.

**Comment by xu-cheng** [comment] 2016-04-12 06:53
Yes, you can. Just to remember to do this at the very last step.

**Comment by sjackman** [comment] 2016-04-12 06:53
What does the `git filter-branch` script do? Is it rewriting history, or creating new commit(s)?

**Comment by xu-cheng** [comment] 2016-04-12 06:54
It's rewriting the entire git history. So you should run it in a separate copy.

**Comment by sjackman** [comment] 2016-04-12 06:55
If it's rewriting history, will it leave the repository in a state that `Homebrew/brew` can be merged into `Linuxbrew/brew`? I'm afraid that they'll have totally different commit histories after it's done.

**Comment by sjackman** [comment] 2016-04-12 06:56
Would a simple `git rm Library/Formula Library/Aliases` be possible?

**Comment by sjackman** [comment] 2016-04-12 06:58
Perhaps the easiest way to find out is just to try it and see what happens. Run the script and then try merging `Homebrew/brew` into `Linuxbrew/brew` and see what happens.

**Comment by sjackman** [comment] 2016-04-12 06:59
If it rewrites history on the `homebrew/master` branch exactly as it did when you ran it, and produces identical results, then maybe the git commit SHA1 will match up. Fingers crossed.

**Comment by xu-cheng** [comment] 2016-04-12 07:01
> If it's rewriting history, will it leave the repository in a state that Homebrew/brew can be merged into Linuxbrew/brew? I'm afraid that they'll have totally different commit histories after it's done.

I dunno. So I would suggest to fork then apply the changes. Or you could use this to find all the different commit http://stackoverflow.com/questions/7566416/different-commits-between-two-branches

> Would a simple git rm Library/Formula Library/Aliases be possible?

But it will introduce a large git history.

> then maybe the git commit SHA1 will match up. Fingers crossed.

I don't think that will happen.

**Comment by sjackman** [comment] 2016-04-12 23:07
What script did you use to create `Linuxbrew/homebrew-core`?

**Comment by sjackman** [comment] 2016-04-13 22:21
`Homebrew/homebrew-core` and `Linuxbrew/linuxbrew-core` agree (have the same SHA1) for the first 62 commits, then the commit `Remove MacPorts and Fink from the build environment` has SHA1 of https://github.com/Homebrew/homebrew-core/commit/ead43565c24ba5139ee8b81095d84e2f54f446b4, whereas in `Homebrew/homebrew-core`, but https://github.com/Linuxbrew/homebrew-core/commit/a6c6c6342f52af34d24bcda0a27fdbfebcd54683 in `Linuxbrew/homebrew-core` because the commit message was rewritten to change `Closes #13` to `Closes Homebrew/homebrew#13`.

```diff
--- linuxbrew
+++ homebrew
@@ -1,10 +1,10 @@
-commit a6c6c6342f52af34d24bcda0a27fdbfebcd54683
+commit ead43565c24ba5139ee8b81095d84e2f54f446b4
 Author: Max Howell <max@methylblue.com>
 Date:   Tue Aug 11 14:46:04 2009 +0100
 
     Remove MacPorts and Fink from the build environment
     
-    Closes #13
+    Closes Homebrew/homebrew#13
 
 diff --git a/Formula/apr.rb b/Formula/apr.rb
 new file mode 100644
```

Do you have the exact script that was used to rewrite the history of `Homebrew/brew` and `Homebrew/homebrew-core`? I'll need to reproduce it exactly to end up with a repository that is compatible with `Homebrew` and can be merged.

**Comment by sjackman** [comment] 2016-04-14 00:09
I'm going to give this a shot:
```sh
git filter-branch -f --prune-empty \
  --index-filter 'git rm --cached --ignore-unmatch -r -q -- Library/Formula Library/Aliases ;' \
  --msg-filter 'sed -Ee "s~\B#[0-9]*~Homebrew/homebrew&~"' \
  -- --all
```

It needs to be fixed up to change `#123` to either `Homebrew/homebrew#123` `Linuxbrew/linuxbrew#123`

**Comment by sjackman** [comment] 2016-04-14 23:07
In https://github.com/Homebrew/brew/commit/a13ff43886f5255694ead2789a65bda3b97dd6b9, the log message `Fixes #10341.` was not rewritten to `Fixes Homebrew/homebrew#10341.`
The spaces between `s` and `#` is a non-breaking space, Unicode point U+00A0 NO-BREAK SPACE.

What regex was used to match issue numbers?

**Comment by sjackman** [comment] 2016-04-14 23:13
Now trying…
```sh
git filter-branch -f --prune-empty \
  --index-filter 'git rm --cached --ignore-unmatch -r -q -- Library/Formula Library/Aliases ;' \
  --msg-filter 'sed -Ee "s~ (#[0-9]+)~ Homebrew/homebrew\1~g"' \
  -- --all
```

**Comment by sjackman** [comment] 2016-04-15 06:05
The commit time stamp of the commit with the log message `tap: add methods to get git related information` changed from `1457243466` to `1457243466`.

```diff
--- a	2016-04-14 22:52:55.000000000 -0700
+++ b	2016-04-14 22:53:35.000000000 -0700
@@ -1,7 +1,7 @@
 tree cdaabac2acce883a57092bf13e85c61e70129b11
 parent a2d0d88bf1915734e1540bef4c9d6c1b403379c7
 author Xu Cheng <xucheng@me.com> 1457179423 +0800
-committer Xu Cheng <xucheng@me.com> 1457243466 +0800
+committer Xu Cheng <xucheng@me.com> 1457199493 +0800
 
 tap: add methods to get git related information
```

```diff
--- /tmp/a	2016-04-14 23:03:16.000000000 -0700
+++ /tmp/b	2016-04-14 23:04:13.000000000 -0700
@@ -1,8 +1,8 @@
-commit 9f96e41b40f52313fbc7832df631827f5e3bcacb
+commit b84983d65528a158c4788f636f83944c0c8361f6
 Author:     Xu Cheng <xucheng@me.com>
 AuthorDate: Sat Mar 5 20:03:43 2016 +0800
 Commit:     Xu Cheng <xucheng@me.com>
-CommitDate: Sun Mar 6 13:51:06 2016 +0800
+CommitDate: Sun Mar 6 01:38:13 2016 +0800
 
     tap: add methods to get git related information
--- /tmp/a	2016-04-14 23:03:16.000000000 -0700
+++ /tmp/b	2016-04-14 23:04:13.000000000 -0700
@@ -1,8 +1,8 @@
-commit 9f96e41b40f52313fbc7832df631827f5e3bcacb
+commit b84983d65528a158c4788f636f83944c0c8361f6
 Author:     Xu Cheng <xucheng@me.com>
 AuthorDate: Sat Mar 5 20:03:43 2016 +0800
 Commit:     Xu Cheng <xucheng@me.com>
-CommitDate: Sun Mar 6 13:51:06 2016 +0800
+CommitDate: Sun Mar 6 01:38:13 2016 +0800
 
     tap: add methods to get git related information
```

**Comment by xu-cheng** [comment] 2016-04-15 07:22
FYI, this is the script I used to create both repos. https://gist.github.com/xu-cheng/a7f788d28ea27c2722ff

I didn't do the git message rewriting. Because I'm not sure whether `#number` should be rewritten to `Homebrew/homebrew#number` or `Linuxbrew/linuxbrew#number` as there will be some overlap.

> The commit time stamp of the commit with the log message.

This is because during the time between I created `Homebrew/brew` to the time we started to use it, all the commits are manually synced from `Homebrew/homebrew` using `git format-patch` and `git am`.

**Comment by xu-cheng** [comment] 2016-04-15 07:24
Also, I don't think you will get same SHA1 eventually. Instead, I suggest you do `git rebase --onto` to force to sync between Homebrew and Linuxbrew.

**Comment by sjackman** [comment] 2016-04-15 16:05
So far I am getting identical SHA1, as long as the commit message and time stamps match identically (and of course the file content). I'm not sure that `git-rebase` will work through the merge commits. If I tried to rebase onto `homebrew/master`, older Linuxbrew commits that no longer apply to the current Homebrew code will conflict. I'd have to deal with possibly dozens to hundreds of merge conflicts.

**Comment by sjackman** [comment] 2016-04-15 23:21
The committer date of 192 revisions changed from `legacy-homebrew` to `brew`.
See http://rpubs.com/sjackman/compare-committer-date

**Comment by sjackman** [comment] 2016-04-15 23:36
Here's the script that I'm testing now. Wish me luck.
```sh
git filter-branch -f --msg-filter 'sed -Ee "s~ (#[0-9]+)~ Linuxbrew/linuxbrew\1~g"' -- 7814c5b9393a7dabc6b78e51bc21a7d3a6999dd2...master
git filter-branch -f --prune-empty \
  --index-filter 'git rm --cached --ignore-unmatch -r -q -- Library/Formula Library/Aliases ;' \
  --msg-filter 'sed -Ee "s~ (#[0-9]+)~ Homebrew/homebrew\1~g"' \
  --env-filter \
'
case $GIT_COMMIT in
235d819edf77fb3fe08714c3cf3489d5de08fc96) export GIT_COMMITTER_DATE="1459665072 +0800";;
1e92c7f4316a2e37d8ec03b73c8e4e3d2b24a18f) export GIT_COMMITTER_DATE="1459665072 +0800";;
48e5079dbddc994f65ce4ddc215479ba46af475e) export GIT_COMMITTER_DATE="1459665072 +0800";;
ef6cbe93363d6e1e579dee56d7e94795f745e25d) export GIT_COMMITTER_DATE="1459656947 +0800";;
e13ff6294a0bbc28fc98d6f797b1b56ce93ecd67) export GIT_COMMITTER_DATE="1459656947 +0800";;
51e4e6490bda0d981afd1787a6392ab588b0601c) export GIT_COMMITTER_DATE="1459656947 +0800";;
ef70efa204c929b01ba0e7a4da843c70ed455313) export GIT_COMMITTER_DATE="1459656947 +0800";;
60f8861ce3dc964f08305237b667f3959de20d45) export GIT_COMMITTER_DATE="1459614849 +0800";;
73bece8744faa316cdde3160a170f4241303032c) export GIT_COMMITTER_DATE="1459613441 +0800";;
fc80d72079b770a516d234f4e0eb8ca50fe063db) export GIT_COMMITTER_DATE="1459613441 +0800";;
c38cbf514d1ead438b235f09a5607faa580b702b) export GIT_COMMITTER_DATE="1459612898 +0800";;
6ed1425b9fb8273ac9b367f08e41ca53afae8b97) export GIT_COMMITTER_DATE="1459612898 +0800";;
71cba6064f73c3e9ea46d10879f1b503bea86586) export GIT_COMMITTER_DATE="1459605096 +0800";;
dc94fbc68a15af37de0691895e7f6247c94ec593) export GIT_COMMITTER_DATE="1459605096 +0800";;
68d6718e53e2d1f155d0261aafb3a3585c425d83) export GIT_COMMITTER_DATE="1459605096 +0800";;
b3aadea002b5fd6847d710929423f13d5af5b0bd) export GIT_COMMITTER_DATE="1459605096 +0800";;
edb7e9f4b539d758ab402f14c48a3effa9316e05) export GIT_COMMITTER_DATE="1459605096 +0800";;
1e33dcb974207fec295516124ab0a2c1a3fa9146) export GIT_COMMITTER_DATE="1459605096 +0800";;
33404b32ef9e8ebbbbcdcecd7ea77e0d2b3a926d) export GIT_COMMITTER_DATE="1459605096 +0800";;
af81f99442ff2616ac10b6e4ea5750e7f953f3d1) export GIT_COMMITTER_DATE="1459605096 +0800";;
74173972ffbb21d314b6b0f4b85af4c2b71f816f) export GIT_COMMITTER_DATE="1459605096 +0800";;
1d13a03cfdb50ec2b014bf82cb5a612e30c0bcbe) export GIT_COMMITTER_DATE="1459605096 +0800";;
deac0d8cca8484b82492cdc68da3feb2a51b795b) export GIT_COMMITTER_DATE="1459605096 +0800";;
bf41e3c44d61c60abc3f07016dc6f1b9175828dc) export GIT_COMMITTER_DATE="1459605096 +0800";;
c831b1efe9e302bed914dcf1119b706b9137ee93) export GIT_COMMITTER_DATE="1459605096 +0800";;
f4a303aa9f194370eb52cda1bd39e97b771449fb) export GIT_COMMITTER_DATE="1459605096 +0800";;
a1a71b8f46ee364a3c096197a9a415c85c9d3dd7) export GIT_COMMITTER_DATE="1459499414 +0800";;
3d622f85544cc4a72a66989c2c85849d8b054295) export GIT_COMMITTER_DATE="1459415422 +0800";;
a9602a5238a91e1f3ad6696c2ee1f02ab7dc6a9d) export GIT_COMMITTER_DATE="1459415422 +0800";;
798ad40e80647a9add30a6714060a759df644192) export GIT_COMMITTER_DATE="1459406941 +0800";;
ee6aa7a78edb91f168b74b3944d64cdeed040cb1) export GIT_COMMITTER_DATE="1459401410 +0800";;
aa60ce7571b98c09c479b58b3c9cfc9edd988fee) export GIT_COMMITTER_DATE="1459401410 +0800";;
be679f91eb6c67c7574485782e4f0cfa456d8ed9) export GIT_COMMITTER_DATE="1459401410 +0800";;
89990349813d9c93beb8ca8c74f78798a1bea01e) export GIT_COMMITTER_DATE="1459239577 +0800";;
64caad7c79208807d595d5189c45e92067b3c8ef) export GIT_COMMITTER_DATE="1459160567 +0800";;
04a99f1eedd993c053053689876de54e169f0992) export GIT_COMMITTER_DATE="1459160567 +0800";;
f1068094455f9b7072cd1e6a3bf1ebec11ea1a4b) export GIT_COMMITTER_DATE="1459160567 +0800";;
0081b8c1060f04422b2134f3975113b6f8f1f7a0) export GIT_COMMITTER_DATE="1458975010 +0800";;
b244376ca6d01fcde6c9d181c8ffd11cf8f11152) export GIT_COMMITTER_DATE="1458975010 +0800";;
32aeb46b6c2d4c95c9cfd4c5b85f62be2553d556) export GIT_COMMITTER_DATE="1458975010 +0800";;
6207527aabffe39a65f41393849b9c3c2ee04425) export GIT_COMMITTER_DATE="1458975010 +0800";;
cddee3c5dfc5721a804787a4760ce0c3251eaf66) export GIT_COMMITTER_DATE="1458975010 +0800";;
d6e5ecff5b89ef6b0b079763b60191be5010986c) export GIT_COMMITTER_DATE="1458975010 +0800";;
be7f2b5b0e72cf6389e8ad76a0cb7128058dc248) export GIT_COMMITTER_DATE="1458802333 +0800";;
c5be64cfa1b8c6dfb5c9df08b95c27a8f445ac99) export GIT_COMMITTER_DATE="1458802333 +0800";;
f38a816f03bf964173f5aadcc637b66062d7e9ab) export GIT_COMMITTER_DATE="1458716488 +0800";;
fe0c3127d088921a7adaaa9429bb110ff48fac3f) export GIT_COMMITTER_DATE="1458711676 +0800";;
2fd4075442849672906aab1d1b12d214a9b64f9c) export GIT_COMMITTER_DATE="1458647056 +0800";;
a1824f82b271b14b93f1f401a1ceb47bee9414a6) export GIT_COMMITTER_DATE="1458644119 +0800";;
eaf0b54999fa52dad729a9793d27963e14713e69) export GIT_COMMITTER_DATE="1458644119 +0800";;
f715e0e48e78a4338a8af7cf5e94715a02f13526) export GIT_COMMITTER_DATE="1458644119 +0800";;
f8a8e876c5b6f7c287e147620ea7a0f4209bbea5) export GIT_COMMITTER_DATE="1458558458 +0800";;
30e7dc8eb12723a754661a5b9e0f26ec2d8c5cfb) export GIT_COMMITTER_DATE="1458558458 +0800";;
a3186130dd7ac3075987b5c9bcbad74de767a64a) export GIT_COMMITTER_DATE="1458558458 +0800";;
cc0fd25ff1caba9520660a2b02179213f13fc76a) export GIT_COMMITTER_DATE="1458558458 +0800";;
51d8d735a106f4f70769cdfd19fb21f64dee8373) export GIT_COMMITTER_DATE="1458456958 +0800";;
e95f61b55a010eac056078ca47878f4e997bc2c8) export GIT_COMMITTER_DATE="1458456958 +0800";;
ac2fe466e03dc8ecbcbb14eb439644bdb68addb9) export GIT_COMMITTER_DATE="1458456958 +0800";;
41998df03cac9d421716ecb573d66c60d6a805bc) export GIT_COMMITTER_DATE="1458456958 +0800";;
291583de2d7fef89a4b5135153630de0f1828065) export GIT_COMMITTER_DATE="1458452898 +0800";;
48cfc1d2ed3041998eca2387003c9960df8f75cc) export GIT_COMMITTER_DATE="1458386090 +0800";;
e0f5b710002a4e7bef647a75a2e13b8b64fdb6ca) export GIT_COMMITTER_DATE="1458386090 +0800";;
c6183aaea9304cc3f0f38583d890004830cc6fe8) export GIT_COMMITTER_DATE="1458386090 +0800";;
8c7f3d859e8f715b6c63e4fe75e7a636aee4167f) export GIT_COMMITTER_DATE="1458386090 +0800";;
e5fa93d36e6505419cd9a3f6d7e15bfe3cdb93a2) export GIT_COMMITTER_DATE="1458386090 +0800";;
5e6cea284d64b43ac4959bc8c1409ddd2442e136) export GIT_COMMITTER_DATE="1458386090 +0800";;
d1793bf0afb46fcf5d7cf945fc1d6b173d523f2c) export GIT_COMMITTER_DATE="1458386090 +0800";;
5cebfce08f50977f1861c5c76cf1eb7d25463837) export GIT_COMMITTER_DATE="1458386090 +0800";;
e1c8965ca9ec7d3f23c1d01c5655e2eb20c5fd0b) export GIT_COMMITTER_DATE="1458386090 +0800";;
5a850cf3a831c2a7e0201561414d7736f7d0c34c) export GIT_COMMITTER_DATE="1457959293 +0800";;
7032591bd44a8f50aaa55574ac97cd5cb7261460) export GIT_COMMITTER_DATE="1457958815 +0800";;
946c6deb4b5168ad2ec15e62aa6e81181e9e246c) export GIT_COMMITTER_DATE="1457956695 +0800";;
0b38f9b286bc61e2b2d2232f80ea8ebc5909fb07) export GIT_COMMITTER_DATE="1457955555 +0800";;
0d2de365e2c9f1be5a623c2602270f225ca07b5f) export GIT_COMMITTER_DATE="1457955555 +0800";;
4b30df263ea85c61ec585b9859a3ba7b9b17e91f) export GIT_COMMITTER_DATE="1457850725 +0800";;
2d5e5133588ac4face3b3e486b9448c52684ffa2) export GIT_COMMITTER_DATE="1457850725 +0800";;
cfef282c5011e39b75329d01b45cfd53f6a10749) export GIT_COMMITTER_DATE="1457850725 +0800";;
f0139e7164f95492cb9ea8007bef26525b83a16f) export GIT_COMMITTER_DATE="1457850725 +0800";;
5a1c57ab88eee6629922c8f4ebc1e1c3b67b0c45) export GIT_COMMITTER_DATE="1457850725 +0800";;
34b4dcf11de0ee024e2b9cd166e17d1f671ef57a) export GIT_COMMITTER_DATE="1457850725 +0800";;
99e15f4192b9d1b402ce36b3eec176df2839c98b) export GIT_COMMITTER_DATE="1457674374 +0800";;
397c202fb0e5a1bb4d03ceb61f54645f09d4aae6) export GIT_COMMITTER_DATE="1457674374 +0800";;
626169d742ea572963e0f7b73762a555e846adbc) export GIT_COMMITTER_DATE="1457606743 +0800";;
1747420b2f65d5f365b989b38880daf8c7a0f318) export GIT_COMMITTER_DATE="1457524046 +0800";;
0aa300507881f52f31203424470b3ebfc3c87faf) export GIT_COMMITTER_DATE="1457523341 +0800";;
d7732afe0581fe63cd2f8791dc4692ef271c5773) export GIT_COMMITTER_DATE="1457516326 +0800";;
9e9dfb6a8dfc5440dac596077bbe7498cf9ded4b) export GIT_COMMITTER_DATE="1457510422 +0800";;
b5f35c8a3e1e200b4c2f18a82084324980b2c816) export GIT_COMMITTER_DATE="1457445309 +0800";;
2a1365dcf09148db64200ebbcd0e7089895aae37) export GIT_COMMITTER_DATE="1457441531 +0800";;
fc3404b2fc7b4c9fda8a67db7193f9d6f25dc10c) export GIT_COMMITTER_DATE="1457440579 +0800";;
0525c9eeea27eff1a6de05e7a01ec268ae07437b) export GIT_COMMITTER_DATE="1457440579 +0800";;
943ea8c3708ec9a56de9f9234702c863e30ca690) export GIT_COMMITTER_DATE="1457440579 +0800";;
e931b19643a6da8326fd454c46b45be1237ebe70) export GIT_COMMITTER_DATE="1457416049 +0800";;
b6c814e2c8aa6fb6180bcc81d7e250d61f458ec4) export GIT_COMMITTER_DATE="1457416049 +0800";;
9cc7a2b7c58838f5d2c9a058b7dbae166e4c97bb) export GIT_COMMITTER_DATE="1457352035 +0800";;
7970035e5d8bdaf201e44b0fa84a047f9f67ab22) export GIT_COMMITTER_DATE="1457351026 +0800";;
d4cb0763050f18b3803f2fba01558041bc5690c7) export GIT_COMMITTER_DATE="1457351026 +0800";;
51b94f3b278543dd482dabd5926148fcfb2e6522) export GIT_COMMITTER_DATE="1457351026 +0800";;
142c94ce0d453e3209f5502238b354658de4e039) export GIT_COMMITTER_DATE="1457351026 +0800";;
82c434aa066d2e4a62c0c2c799c8caf4b6e21bca) export GIT_COMMITTER_DATE="1457351026 +0800";;
fbcd95b1634f8cfbdc04c90701515e81368e6501) export GIT_COMMITTER_DATE="1457243466 +0800";;
73e5d38c3592115a74c7004b475fc26cfa974f2c) export GIT_COMMITTER_DATE="1457243466 +0800";;
esac
' \
   -- --all
```

**Comment by sjackman** [comment] 2016-04-17 15:48
This commit very nearly works. Up until now, the graph topology of the commits have remained unchanged. An empty merge commit was removed with the mesage `Merge remote-tracking branch 'origin/master'` which is the parent commit of `Avoid pathological trailing slash` in `legacy-homebrew`, but in `brew` this merge commit does not exist, and the parent commit is `Formula Cookbook: /environmental/environment/`.

I was hoping that `git filter-branch --prune-empty` would remove empty merge commits, but it explicitly does not (`this switch only applies for commits that have one and only one parent`). Googling for `git filter-branch prune empty merge commits` shows other people trying to accomplish this same task.

**Comment by sjackman** [comment] 2016-04-17 17:05
Unfortunately there's an older empty merge commit that was not removed from `brew`, `001b8de Merge branch 'qt5'`, so it's important not to remove empty merge commits from the entire git commit history, but only commits after `001b8de Merge branch 'qt5' 2014-01-11 15:58:34 +0000`

**Comment by sjackman** [comment] 2016-04-17 17:32
This script removes empty merge commits after and not including `001b8de Merge branch 'qt5' 2014-01-11 15:58:34 +0000`.

```sh
git filter-branch -f --prune-empty --parent-filter '
ruby -e '"'"'
old_parents = gets.chomp.gsub("-p ", " ")
new_parents = if old_parents.empty? then
  []
else
  `git show-branch --independent #{old_parents}`.split
end
puts new_parents.map{|p| "-p " + p}.join(" ")
'"'" \
-- 001b8de679e776516ae266699e40d403945137d2..master
```

**Comment by sjackman** [comment] 2016-04-17 17:44
It works! The above two scripts can take the existing `Linuxbrew/linuxbrew` repository and rewrite its history so that every commit in `Homebrew/brew` has a corresponding commit with an identical SHA1 in the newly created `Linuxbrew/brew` repository. To accomplish this feat, the exact same transformations that were applied to `Homebrew/homebrew` to create `Homebrew/brew` must be repeated exactly. Those transformations include:

1. **tree-filter**: Remove the directories `Library/Formula` and `Library/Aliases`
2. **msg-filter**: Change issue references like `#123` to `Homebrew/homebrew#123`
3. **env-filter**: Change the `committer author` and `committer date` of 103 revisions listed above.
4. **parent-filter**: Remove empty merge commits after and not including `001b8de Merge branch 'qt5' 2014-01-11 15:58:34 +0000.` but do not remove empty merge commits before that commit

The resulting repository is at https://github.com/Linuxbrew/brew

**Comment by sjackman** [comment] 2016-04-17 17:58
I'm going to tackle `Homebrew/homebrew-core` now.

**Comment by sjackman** [comment] 2016-04-17 18:39
Here's the scripts with some explanation: https://github.com/sjackman/rewrite-git-history
It has the scripts for `brew`. I'll add the scripts for `homebrew-core` probably later tonight if it goes well.

**Closed** 2016-05-02 06:49 UTC
Labels: enhancement, in progress
