### ISSUE TITLE
Problems building mercurial for packer in sjackman/linuxbrew Docker container.

### ISSUE THREAD

**Issue by hartzell** [Linuxbrew/linuxbrew#866] opened 2016-02-29 00:46 UTC
# Please follow the general troubleshooting steps first:

- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [x] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?

---

I'm trying to touch up the recipe for packer (I have another pull request open which balled a bunch of changes together, I'm redoing them 1 by 1).

I'm working in an `sjackman/linuxbrew` Docker image.

After touching up the OS value in the formula, `brew install packer` starts building mercurial, which dies for lack of Python (even though /usr/bin/python in the container is v2.7.6).  Here's the [gist-log](https://gist.github.com/anonymous/557593ffd579dad1f4f7) that the error message suggests.

After I add a dependency on Python, I still have troubles.  The details are [in this gist](https://gist.github.com/hartzell/c6800ae8e9ee093c1f57).    In short, when I `build install packer` it complains about not being able to find ncurses in homebrew/dupes (which I have not yet tapped).  When I `brew install mercurial` directly, it taps it for me but then the installation fails.

I could use some help understanding what's going wrong.

**Comment by sjackman** [comment] 2016-02-29 19:56
```
mercurial/base85.c:13:20: fatal error: Python.h: No such file or directory
 #include <Python.h>
```
https://gist.github.com/anonymous/557593ffd579dad1f4f7#file-01-make-L18

That's fixed by either `brew install python` or `sudo apt-get install python-dev` or `sudo yum install python-devel`.

**Comment by sjackman** [comment] 2016-02-29 20:00
```
Error: No available formula with the name "homebrew/dupes/ncurses"
Please tap it and then try again: brew tap homebrew/dupes
```
https://gist.github.com/hartzell/c6800ae8e9ee093c1f57#file-install-output-txt-L18

I wasn't able to reproduce this error myself. Have you updated the docker image? `docker pull sjackman/linuxbrew`.

**Comment by hartzell** [comment] 2016-03-01 02:12
If mercurial depends on Python (in the sense that you need to provide it somehow) shouldn't it depend on it in the Formula?

Can the formula tell whether a prerequisite has been provided via brew or apt-get/yum/...?  Should it care?

**Comment by hartzell** [comment] 2016-03-01 04:40
I pulled/updated the container and have a different problem, an issue trying to make a hardlink from zipinfo to unzip.  It suspect that I'm mis-using Docker somehow.  Suggestions welcome.

I've uploaded the commands that I'm running the result I'm seeing into [this gist](https://gist.github.com/hartzell/9d09aa3ca1ed3e329165).

I'm not working with the copy of linuxbrew in ~/.linuxbrew, but cloning my own so that I can make changes to push back to the project.  That might be an unsupported model for using the container.

**Comment by sjackman** [comment] 2016-03-01 22:26
> If mercurial depends on Python (in the sense that you need to provide it somehow) shouldn't it depend on it in the Formula?

Yes, probably. I want to avoid installing the Homebrewed `python` if the system's `python` can be used, so I've avoided adding a hard `"python"` dependency to formulas. The Python requirement logic needs to be improved for Linuxbrew.

**Comment by sjackman** [comment] 2016-03-01 22:28
I'm not able to reproduce that `unzip` issue. It looks like a Docker issue/bug. Perhaps it's specific to the version of Docker. I'm using `Docker version 1.7.1, build 786b29d`.

**Comment by sjackman** [comment] 2016-03-01 22:29
> I'm not working with the copy of linuxbrew in ~/.linuxbrew, but cloning my own so that I can make changes to push back to the project. That might be an unsupported model for using the container.

You can add your own remote to `~/.linuxbrew` using `git remote add hartzell https://github.com/hartzell/linuxbrew.git`. Cloning your own is fine too, but I find the remote easier.

**Comment by hartzell** [comment] 2016-03-13 18:06
The unzip issue is a [virtualbox/vboxfs problem](https://www.virtualbox.org/ticket/818), and [here](https://github.com/docker/machine/issues/1876).

I'll work on this in another setting.

**Closed** 2016-03-13 20:26 UTC
Labels: build-error

**Comment by sjackman** [comment] 2016-03-14 18:30
Thanks! That's helpful.
