### ISSUE TITLE
curl: Failed to download resource: Connection timed out

### ISSUE THREAD

**Issue by Neraste** [Linuxbrew/linuxbrew#797] opened 2016-02-09 15:53 UTC
Hi there

Downloading main package of a formula is fine, but downloading its resources fails. Curls ends up with timeout error.

Example with `brew install -v git`, when attempting to download git-manpages:

```
==> Downloading https://www.kernel.org/pub/software/scm/git/git-manpages-2.6.1.tar.xz
/location/to/linuxbrew/opt/curl/bin/curl -fLA Homebrew 0.9.5 (Ruby 1.9.1-378; x86_64-linux) https://www.kernel.org/pub/software/scm/git/git-manpages-2.6.1.tar.xz -C 0 -o /home/me/.cache/Homebrew/git--man-2.6.1.tar.xz.incomplete
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:03:08 --:--:--     0curl: (7) Failed to connect to www.kernel.org port 443: Connection timed out
Error: Failed to download resource "git--man"
Download failed: https://www.kernel.org/pub/software/scm/git/git-manpages-2.6.1.tar.xz
```

However, when trying the used curl command in my prompt, with  quotes added around the user agent string, it just works:

```shell
$ /location/to/linuxbrew/opt/curl/bin/curl -fLA "Homebrew 0.9.5 (Ruby 1.9.1-378; x86_64-linux)" https://www.kernel.org/pub/software/scm/git/git-manpages-2.6.1.tar.xz -C 0 -o /home/me/.cache/Homebrew/git--man-2.6.1.tar.xz.incomplete
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  372k  100  372k    0     0   243k      0  0:00:01  0:00:01 --:--:--  243k
```

So, the file is available and curl can download it, but not when called by Linuxbrew. What is wrong?

Output of `brew config`:
```
HOMEBREW_VERSION: 0.9.5
ORIGIN: http://github.com/Homebrew/linuxbrew.git
HEAD: da44282a3499494d27bf923758bbfd0481ab7a2e
Last commit: 3 months ago
HOMEBREW_PREFIX: /location/to/linuxbrew
HOMEBREW_REPOSITORY: /location/to/linuxbrew
HOMEBREW_CELLAR: /location/to/linuxbrew/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://linuxbrew.bintray.com
CPU: quad-core 64-bit 6
OS X: 0-x86_64
Xcode: N/A
CLT: N/A
Clang: N/A
X11: N/A
System Ruby: 1.9.1-p378 => /usr/local/ruby-1.9.1/bin/ruby
Perl: /usr/bin/perl
Python: /usr/local/python/bin/python => /usr/local/python-2.7.5/bin/python2.7
Ruby: /usr/local/bin/ruby => /usr/local/ruby-1.9.1/bin/ruby
Java: 1.7.0_95
```

**Comment by sjackman** [comment] 2016-02-09 17:41
I can't say. Can you confirm that the issue persists today? I just tried a `brew fetch git`, and it works for me.

```
$ brew fetch git
==> Downloading https://www.kernel.org/pub/software/scm/git/git-2.7.0.tar.xz
######################################################################## 100.0%
Downloaded to: /home/sjackman/.cache/Homebrew/git-2.7.0.tar.xz
SHA1: c9b9adf97236eee084608d1d8a1754ae851897fa
SHA256: fa9fb34efce9c80527152a40fbae138e83bd04a15ef9111726252259345a7b0d
Resource: man
==> Downloading https://www.kernel.org/pub/software/scm/git/git-manpages-2.7.0
######################################################################## 100.0%
Downloaded to: /home/sjackman/.cache/Homebrew/git--man-2.7.0.tar.xz
SHA1: 20730ec58479989e357f85826dfc3384f1311f79
SHA256: b7f255aa17a5d06b9b71f6e3957f65e8f15789b2d31f09b1c2bf697a21458a0d
Resource: html
==> Downloading https://www.kernel.org/pub/software/scm/git/git-htmldocs-2.7.0
######################################################################## 100.0%
Downloaded to: /home/sjackman/.cache/Homebrew/git--html-2.7.0.tar.xz
SHA1: 4fc029b470b90e4678e26fd0129d1a77e9151434
SHA256: a9d30a744eb07392ba3ffe389cca7e57a2bdd718c9ffccdf2d525eeafac548a9
```

**Comment by Neraste** [comment] 2016-02-09 18:12
Well, `brew fetch git` works fine. Then, `brew install git` succeeded. That is weird...

**Comment by sjackman** [comment] 2016-02-09 18:22
I'm going to close this issue. Please comment if you're able to reproduce the issue. It may have been a transient network error.

**Comment by OmeGak** [comment] 2016-02-11 09:15
I'm also affected by this. I can't install any formula without manually fetching it first.

```
brew install hello
==> Downloading http://ftpmirror.gnu.org/hello/hello-2.10.tar.gz
Error: Failed to download resource "hello"
Download failed: http://ftpmirror.gnu.org/hello/hello-2.10.tar.gz
```

```
brew fetch hello
==> Downloading http://ftpmirror.gnu.org/hello/hello-2.10.tar.gz
==> Downloading from http://mirror.switch.ch/ftp/mirror/gnu/hello/hello-2.10.tar.gz
######################################################################## 100.0%
Downloaded to: /home/omegak/.cache/Homebrew/hello-2.10.tar.gz
SHA1: f7bebf6f9c62a2295e889f66e05ce9bfaed9ace3
SHA256: 31e066137a962676e89f69d1b65382de95a7ef7d914b8cb956f41ea72e0f516b
```

```
brew install hello
==> Downloading http://ftpmirror.gnu.org/hello/hello-2.10.tar.gz
Already downloaded: /home/omegak/.cache/Homebrew/hello-2.10.tar.gz
==> ./configure --disable-silent-rules --prefix=/home/omegak/.linuxbrew/Cellar/hello/2.10
^C
```

**Comment by sjackman** [comment] 2016-02-11 16:58
As a workaround, you can fetch the formula and its dependencies using `brew fetch --deps hello`.

Thanks for confirming the bug. It's very strange. As I'm not able to reproduce the error, it's going to be difficult to troubleshoot. Please remove the cached source and gist the logs.

```sh
rm -f `brew --cache hello`
brew install hello || brew gist-logs hello
```

**Comment by OmeGak** [comment] 2016-02-12 09:09
The failed download doesn't produce any log, apparently.

```
$ rm -f `brew --cache hello`
$ brew install -v hello || brew gist-logs hello
==> Downloading http://ftpmirror.gnu.org/hello/hello-2.10.tar.gz
/home/omegak/.linuxbrew/opt/curl/bin/curl -fLA Homebrew 0.9.5 (Ruby 2.2.3-173; x86_64-linux) http://ftpmirror.gnu.org/hello/hello-2.10.tar.gz -C 0 -o /home/omegak/.cache/Homebrew/hello-2.10.tar.gz.incomplete
Error: Failed to download resource "hello"
Download failed: http://ftpmirror.gnu.org/hello/hello-2.10.tar.gz
Error: No logs.
```

**Comment by Neraste** [comment] 2016-02-12 17:58
Fetching the dependencies doesn't work in some cases: diff files cannot be fetched. The download fails due to time out, but again, using the curl command outputed in verbose mode works fine.

By instance: ```readline```.

I am wondering (this is highly hypothetical), is there something special with the curl binary used and its parameters? In some cases, if I do not put ```location``` in my ```curlrc```, it doesn't follow HTTP 302 redirection, even if there is the ```-L``` parameter. Moreover, I am behind a proxy. ```brew doctor ``` complains about the ```curlrc``` file, but how can I pass the proxy parameter otherwise?

**Comment by Neraste** [comment] 2016-02-12 18:09
OK, I have to export ```all_proxy``` with my proxy inside to solve this, even if it is defined in my ```curlrc``` file. So, why does not curl read its config file?

**Comment by sjackman** [comment] 2016-02-12 18:16
Please report
```
which -a curl
curl --version
brew list --versions curl
```

> brew doctor complains about the curlrc file, but how can I pass the proxy parameter otherwise?

Try setting the environment variable.
```sh
export ALL_PROXY=…
```

> OK, I have to export all_proxy with my proxy inside to solve this, even if it is defined in my curlrc file. 

Ah, did setting the `ALL_PROXY` environment variable solve your issue?

> So, why does not curl read its config file?

Mystery to me. You could try troubleshooting with…

```sh
strace -e open curl http://google.ca
```

**Comment by Neraste** [comment] 2016-02-12 18:32
> Ah, did setting the ```ALL_PROXY``` environment variable solve your issue?

Yes. At least, it seems.

For the next, I will answer in few days.

**Comment by OmeGak** [comment] 2016-02-15 07:47
Reporting.

```
which -a curl
/home/omegak/.linuxbrew/bin/curl
/usr/bin/curl
```

```
curl --version
curl 7.47.1 (x86_64-pc-linux-gnu) libcurl/7.47.1 OpenSSL/1.0.2f zlib/1.2.8
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp smb smbs smtp smtps telnet tftp 
Features: IPv6 Largefile NTLM NTLM_WB SSL libz TLS-SRP UnixSockets 
```

```
brew list --versions curl
curl 7.47.1 7.45.0
```

**Comment by sjackman** [comment] 2016-02-16 01:09
My quick test indicates that the Linuxbrewed `curl` does read the file `~/.curlrc`. Please report
```sh
cat ~/.curlrc
```

**Comment by OmeGak** [comment] 2016-02-16 09:22
No such file.

**Comment by sjackman** [comment] 2016-02-16 18:42
Sorry, I was addressing the original poster, @Neraste.

> OK, I have to export all_proxy with my proxy inside to solve this, even if it is defined in my curlrc file. So, why does not curl read its config file?

I believe that `curl` does read its config file.

**Comment by OmeGak** [comment] 2016-02-17 11:02
I still think there's some issue here. I can download just fine things from `curl` and `brew fetch`, but not from `brew install`.

```
brew -v install hello                                                                                                                                                                                                                                                                                                       
==> Downloading http://ftpmirror.gnu.org/hello/hello-2.10.tar.gz
/home/omegak/.linuxbrew/opt/curl/bin/curl -fLA Homebrew 0.9.5 (Ruby 2.2.3-173; x86_64-linux) http://ftpmirror.gnu.org/hello/hello-2.10.tar.gz -C 0 -o /home/omegak/.cache/Homebrew/hello-2.10.tar.gz.incomplete
Error: Failed to download resource "hello"
Download failed: http://ftpmirror.gnu.org/hello/hello-2.10.tar.gz
```

I then go and try `curl` directly and it works:

```
/home/omegak/.linuxbrew/opt/curl/bin/curl -fLA "Homebrew 0.9.5 (Ruby 2.2.3-173; x86_64-linux)" http://ftpmirror.gnu.org/hello/hello-2.10.tar.gz -C 0 -o /home/omegak/.cache/Homebrew/hello-2.10.tar.gz.incomplete
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   329  100   329    0     0    272      0  0:00:01  0:00:01 --:--:--  1788
100  708k  100  708k    0     0   528k      0  0:00:01  0:00:01 --:--:--  528k
```

The only difference is that I had to quote `Homebrew 0.9.5 (Ruby 2.2.3-173; x86_64-linux)`.
Any suggestion on how to keep investigating this?

**Comment by Neraste** [comment] 2016-02-17 13:56
> I believe that curl does read its config file.

I don't think so. If I don't `export all_proxy=http://myproxy`, even if there is a `proxy = http://myproxy` in my `.curlrc`, curl isn't able to connect to server.

@OmeGak Are you behind a proxy?

**Comment by sjackman** [comment] 2016-02-17 18:30
It is strange that `brew fetch` should work but not `brew install`.
Shouldn't `export all_proxy=http://myproxy` be `export ALL_PROXY=http://myproxy`?
Please report…
```sh
cat ~/.curlrc
curl --version
echo xyz >>~/.curlrc
curl --version
```

**Comment by OmeGak** [comment] 2016-02-18 09:15
@Neraste, as far as I know I'm not behind a proxy.

**Comment by Neraste** [comment] 2016-02-18 11:06
@OmeGak proxy was what blocked my connection

@sjackman `all_proxy` should be [lowercase](https://unix.stackexchange.com/questions/212894/whats-the-right-format-for-the-http-proxy-environment-variable-caps-or-no-ca), but for curl there is no difference, AFAIK.

Here the output you wanted:

```
$ cat .curlrc
proxy = http://myproxy
insecure
location
$ curl --version
curl 7.47.1 (x86_64-pc-linux-gnu) libcurl/7.47.1 OpenSSL/1.0.2f zlib/1.2.8
Protocols: dict file ftp ftps gopher http https imap imaps pop3 pop3s rtsp smb smbs smtp smtps telnet tftp 
Features: IPv6 Largefile NTLM NTLM_WB SSL libz TLS-SRP UnixSockets
$ echo xyz >>~/.curlrc
$ curl --version
Warning: /home/pzehner/.curlrc:4: warning: 'xyz' is unknown
curl 7.47.1 (x86_64-pc-linux-gnu) libcurl/7.47.1 OpenSSL/1.0.2f zlib/1.2.8
Protocols: dict file ftp ftps gopher http https imap imaps pop3 pop3s rtsp smb smbs smtp smtps telnet tftp 
Features: IPv6 Largefile NTLM NTLM_WB SSL libz TLS-SRP UnixSockets
```
But there is nothing new. I mean, I have no problem using curl from command line. Curl called from command line read its curlrc file. The problem is when called by Brew.

**Comment by sjackman** [comment] 2016-02-18 20:03
Try
```sh
export HOMEBREW_VERBOSE=1 HOMEBREW_CURL_VERBOSE=1 
brew install hello
brew fetch hello
```

**Comment by OmeGak** [comment] 2016-02-19 13:06
Reporting with `util-linux`. `hello` link seems to be down.

```
$ export HOMEBREW_VERBOSE=1 HOMEBREW_CURL_VERBOSE=1 
```

```
$ brew install util-linux                          
==> Downloading https://www.kernel.org/pub/linux/utils/util-linux/v2.27/util-linux-2.27.1.tar.xz
/home/omegak/.linuxbrew/opt/curl/bin/curl -fLA Homebrew 0.9.5 (Ruby 2.2.3-173; x86_64-linux) https://www.kernel.org/pub/linux/utils/util-linux/v2.27/util-linux-2.27.1.tar.xz -C 0 -o /home/omegak/.cache/Homebrew/util-linux-2.27.1.tar.xz.incomplete --verbose
Warning: /home/omegak/.curlrc:1: warning: 'xyz' is unknown
Error: Failed to download resource "util-linux"
Download failed: https://www.kernel.org/pub/linux/utils/util-linux/v2.27/util-linux-2.27.1.tar.xz
```

```
$ brew fetch util-linux
==> Downloading https://www.kernel.org/pub/linux/utils/util-linux/v2.27/util-linux-2.27.1.tar.xz
/home/omegak/.linuxbrew/opt/curl/bin/curl -fLA Homebrew 0.9.5 (Ruby 2.2.3-173; x86_64-linux) https://www.kernel.org/pub/linux/utils/util-linux/v2.27/util-linux-2.27.1.tar.xz -C 0 -o /home/omegak/.cache/Homebrew/util-linux-2.27.1.tar.xz.incomplete --verbose
Warning: /home/omegak/.curlrc:1: warning: 'xyz' is unknown
*   Trying 198.145.20.140...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0* Connected to www.kernel.org (198.145.20.140) port 443 (#0)
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: /home/omegak/.linuxbrew/etc/openssl/cert.pem
  CApath: none
* TLSv1.2 (OUT), TLS header, Certificate Status (22):
} [5 bytes data]
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
} [512 bytes data]
* TLSv1.2 (IN), TLS handshake, Server hello (2):
{ [111 bytes data]
* NPN, negotiated HTTP1.1
{ [5 bytes data]
* TLSv1.2 (IN), TLS handshake, Certificate (11):
{ [3585 bytes data]
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
{ [589 bytes data]
* TLSv1.2 (IN), TLS handshake, Server finished (14):
{ [4 bytes data]
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
} [70 bytes data]
* TLSv1.2 (OUT), TLS change cipher, Client hello (1):
} [1 bytes data]
* TLSv1.2 (OUT), TLS handshake, Unknown (67):
} [36 bytes data]
* TLSv1.2 (OUT), TLS handshake, Finished (20):
} [16 bytes data]
* TLSv1.2 (IN), TLS change cipher, Client hello (1):
{ [1 bytes data]
* TLSv1.2 (IN), TLS handshake, Finished (20):
{ [16 bytes data]
* SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256
* ALPN, server did not agree to a protocol
* Server certificate:
*        subject: description=MGg8751JzNRM4B4E; C=US; ST=California; L=San Francisco; O=The Linux Foundation; CN=www.kernel.org; emailAddress=webmaster@kernel.org
*        start date: Apr  9 01:01:47 2014 GMT
*        expire date: Apr  8 15:03:50 2016 GMT
*        subjectAltName: www.kernel.org matched
*        issuer: C=IL; O=StartCom Ltd.; OU=Secure Digital Certificate Signing; CN=StartCom Class 2 Primary Intermediate Server CA
*        SSL certificate verify ok.
} [5 bytes data]
> GET /pub/linux/utils/util-linux/v2.27/util-linux-2.27.1.tar.xz HTTP/1.1
> Host: www.kernel.org
> User-Agent: Homebrew 0.9.5 (Ruby 2.2.3-173; x86_64-linux)
> Accept: */*
> 
{ [5 bytes data]
< HTTP/1.1 200 OK
< Server: nginx
< Date: Fri, 19 Feb 2016 13:05:12 GMT
< Content-Type: application/x-xz
< Content-Length: 3964512
< Connection: keep-alive
< Last-Modified: Mon, 02 Nov 2015 11:06:37 GMT
< ETag: "3c7e60-5238cc55aa940"
< Accept-Ranges: bytes
< Strict-Transport-Security: max-age=15768000
< X-Frame-Options: DENY
< 
{ [3850 bytes data]
100 3871k  100 3871k    0     0  1529k      0  0:00:02  0:00:02 --:--:-- 1530k
* Connection #0 to host www.kernel.org left intact
Downloaded to: /home/omegak/.cache/Homebrew/util-linux-2.27.1.tar.xz
SHA1: 462bca6320535d39b62216d8609da5531bfef0bb
SHA256: 0a818fcdede99aec43ffe6ca5b5388bff80d162f2f7bd4541dca94fecb87a290
==> Verifying util-linux-2.27.1.tar.xz checksum
```

**Comment by sjackman** [comment] 2016-02-19 16:45
The two command lines are identical, and both are reading the `~/.curlrc`. That's a real mystery. Any idea why curl didn't displays its verbose output in the first case? That's where the verbose output would be useful.

**Comment by OmeGak** [comment] 2016-02-22 10:44
I'd say `curl` fails even before it starts downloading on `brew install`.

I don't know much about the internals of homebrew, but I gather that that both `brew install` and `brew fetch` make use of `Resource` class, end up calling `fetch` on it eventually and there is where `DownloadError` is raised. 

I have no idea why or how, but it seems the problem comes from [here](https://github.com/Linuxbrew/linuxbrew/blob/8dd8144a3845817f51aa44b06c194f25f3013d53/Library/Homebrew/download_strategy.rb#L300).

I'll probably add some print statements there to see if I spot the difference.

**Comment by sjackman** [comment] 2016-02-23 18:13
@biocyberman is also experiencing this issue. I haven't been able to reproduce it yet myself, so I'm having difficult troubleshooting it. Can everyone experiencing this issue please report the following? I'm curious to see if you're all perhaps using the same distribution of Linux.
```sh
brew config |egrep 'OS|Linuxbrew'
```
You may want to also try recompiling `curl` with the Homebrewed `gcc` and see if that helps.
```sh
brew install gcc
brew reinstall curl
```

**Comment by OmeGak** [comment] 2016-02-25 08:12
Just reinstalled `curl` with homebrewed `gcc` and nothing changes. `brew test curl` works fine, though.
Reporting `brew config`:

```
$ brew config | egrep 'OS|Linuxbrew'
HOMEBREW_REPOSITORY: /home/omegak/.linuxbrew
OS: elementary OS Freya
OS glibc: 2.19
OS gcc: 4.8.4
Linuxbrew glibc: 2.19
Linuxbrew gcc: 5.3.0
```

**Comment by OmeGak** [comment] 2016-02-25 09:47
A bit more research on my end.

The error is definitely coming from [here](https://github.com/Linuxbrew/linuxbrew/blob/8dd8144a3845817f51aa44b06c194f25f3013d53/Library/Homebrew/download_strategy.rb#L327).

The parameters passed to `curl`, both for `install` and `fetch` (util-linux) are:
* **@url**: `https://www.kernel.org/pub/linux/utils/util-linux/v2.27/util-linux-2.27.1.tar.xz`
* **downloaded_size**: `28672`
* **temporary_path**: `/home/omegak/.cache/Homebrew/util-linux-2.27.1.tar.xz.incomplete`

So it seems in principle the call is exactly the same, but the outcome is that `brew install` fails immediately after calling `curl` with at least the an url and `HOMEBREW_CURL_VERBOSE=1` doesn't make it show more information.

I added `system("which curl")` statement right before and in both cases the binary being used is `/home/omegak/.linuxbrew/bin/curl`.

Any idea on where to check next?

**Comment by sjackman** [comment] 2016-02-25 17:23
> The error is definitely coming from here.

What makes you say that? Were you able to work around the issue by changing the `curl` parameters in `_fetch`?

**Comment by sjackman** [comment] 2016-02-25 17:58
This `curl` issue and this `python` issue #841 may be related.
Can someone here try this patch and report whether it works around the problem?
```diff
diff --git a/Library/Homebrew/extend/ENV/std.rb b/Library/Homebrew/extend/ENV/std.rb
index ea1b4d8..42b2ec7 100644
--- a/Library/Homebrew/extend/ENV/std.rb
+++ b/Library/Homebrew/extend/ENV/std.rb
@@ -58,6 +58,7 @@ module Stdenv

     if OS.linux? && !["glibc", "glibc25"].include?(formula && formula.name)
       # Add this formula's library directory to the shared library search path.
+      FileUtils.mkdir_p formula.lib if formula
       prepend "LD_LIBRARY_PATH", formula.lib, File::PATH_SEPARATOR if formula

       # Set the dynamic linker and library search path.
```

**Comment by sjackman** [comment] 2016-02-25 19:49
I've recently fixed #841. This fix *may* also fix this issue. Could people here please `brew update` and test? Thanks!

**Comment by OmeGak** [comment] 2016-02-26 08:48
I simply tried passing different stuff to `curl` modifying but I didn't manage to work around the issue. But it finally works for me after `brew update`. :wink: 

This was a tricky one. Thanks a lot for the patience!

**Comment by sjackman** [comment] 2016-02-28 04:06
A lot of the credit is owed to @erigler-usgs. It would have taken me ages to figure this one out on my own.

**Closed by sjackman** 2016-02-28 04:06 UTC
Labels: build-error, help wanted
